project:
  type: website

website:
  title: "Climate Causality & Attribution"
  description: "Homepage of the Climate Causality & Attribution working group of the University Leipzig"
  site-url: https://lim-climate-causality.github.io/
  favicon: images/logos/logo_small.png
  navbar:
    background: "#EDEDF5" 
    foreground: "#712119"
    search: true
    pinned: true       # Set false to hide navbar while scrolling
    logo: images/logos/logo_small.png
    right:
      - href: index.qmd#about
        text: "About"
      - href: index.qmd#research
        text: "Research"
      - href: index.qmd#projects
        text: "Projects"
      - href: index.qmd#people
        text: "People"
      - text: Publications
        menu: 
          - href: publications/index.qmd
            text: Papers
          - href: publications/software/index.qmd
            text: Software
      - text: "Contact Us"
        menu:  
          - href: index.qmd#contact
            text: "Contact"
          - href: tenders/index.qmd
            text: "Open Positions"

      - href: https://github.com/LIM-Climate-Causality/lim-climate-causality.github.io
        icon: github

  page-footer:
    background: "#712119"
    left: |
      [IMPRESSUM](/impressum.qmd)
    center:
      - href: https://github.com/LIM-Climate-Causality/lim-climate-causality.github.io
        icon: github
      - href: mailto:marlene.kretschmer@uni-leipzig.de
        icon: envelope
    right:
      - text: Copyright © ClimCA 2025


  announcement:
    icon: lightbulb-fill
    dismissable: true
    content: "New open positions available! [Click here to check them out](tenders/index.qmd)."
    type: secondary
    position: above-navbar

format:
  html:
    fontsize: 1.15rem
    css: [theme.css , custom_theme.scss]
    code-overflow: scroll
    linkcolor: "#712119"
    include-in-header: 
      - dropdown.js
      - progress-bar.html
      - text: <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    title-block-banner: true
    anchor-sections: false



